# Kullanıcı Aktivite İzleme Sistemi - Windows Server
# Tek Komutla Otomatik Kurulum
# Kullanım: PowerShell'i Yönetici olarak açın ve çalıştırın:
#   .\install_windows.ps1
# Veya: Invoke-WebRequest -Uri "https://your-domain.com/install_windows.ps1" -OutFile install.ps1; .\install.ps1

$ErrorActionPreference = "Stop"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Kullanıcı Aktivite İzleme Sistemi" -ForegroundColor Cyan
Write-Host "Windows - Otomatik Kurulum" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Yönetici kontrolü
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "[HATA] Bu script YÖNETİCİ olarak çalıştırılmalıdır!" -ForegroundColor Red
    Write-Host "PowerShell'i 'Yönetici olarak çalıştır' ile açın." -ForegroundColor Yellow
    exit 1
}

# Yapılandırma
$InstallDir = "C:\ProgramData\user_activity_monitor"
$ScriptPath = "$InstallDir\user_activity_monitor.py"
$EnvPath = "$InstallDir\user_activity_monitor.env"
$ServiceName = "UserActivityMonitor"
$NSSMPath = "$InstallDir\nssm.exe"
$LogDir = "$InstallDir\logs"

Write-Host "[1/8] Python kontrol ediliyor..." -ForegroundColor Yellow
try {
    $pythonVersion = python --version 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Python bulunamadı"
    }
    Write-Host "       Python bulundu: $pythonVersion" -ForegroundColor Green
    $pythonPath = (Get-Command python).Source
    Write-Host "       Python yolu: $pythonPath" -ForegroundColor Gray
} catch {
    Write-Host "[HATA] Python bulunamadı!" -ForegroundColor Red
    Write-Host "       Lütfen Python 3.x kurun: https://www.python.org/downloads/" -ForegroundColor Yellow
    Write-Host "       Kurulum sırasında 'Add Python to PATH' seçeneğini işaretleyin." -ForegroundColor Yellow
    exit 1
}

Write-Host ""
Write-Host "[2/8] Python paketleri kontrol ediliyor..." -ForegroundColor Yellow
try {
    $null = python -c "import requests" 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "       ✓ requests yüklü" -ForegroundColor Green
    } else {
        Write-Host "       requests kuruluyor..." -ForegroundColor Yellow
        python -m pip install requests --quiet
        Write-Host "       ✓ requests kuruldu" -ForegroundColor Green
    }
} catch {
    Write-Host "[HATA] Paket kurulumu başarısız!" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "[3/8] Kurulum klasörü oluşturuluyor..." -ForegroundColor Yellow
if (-not (Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
    Write-Host "       Klasör oluşturuldu: $InstallDir" -ForegroundColor Green
} else {
    Write-Host "       Klasör zaten var: $InstallDir" -ForegroundColor Gray
}

if (-not (Test-Path $LogDir)) {
    New-Item -ItemType Directory -Path $LogDir -Force | Out-Null
}

Write-Host ""
Write-Host "[4/8] Python scripti oluşturuluyor..." -ForegroundColor Yellow

# Python script içeriği (base64 encoded - PowerShell parser sorunlarını önlemek için)
# Base64 chunks - PowerShell parser sorunlarını önlemek için küçük parçalara bölündü
$base64Chunks = @(
    'IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIKS2Fwc2FtbMSxIEt1bGxhbsSxY8SxIEFrdGl2aXRlIMSwemxlbWUgU2lzdGVtaSAtIFdpbmRvd3MgU2VydmVyClTDvG0ga3VsbGFuxLFjxLEgYWt0aXZpdGVsZXJpbmkgaXpsZXI6IGxvZ2luLCBsb2dvdXQsIHByb2Nl',
    'c3MsIGZpbGUgYWNjZXNzLCByZWdpc3RyeQoiIiIKCmltcG9ydCBvcwppbXBvcnQgcmUKaW1wb3J0IGpzb24KaW1wb3J0IHRpbWUKaW1wb3J0IHNvY2tldAppbXBvcnQgc3VicHJvY2VzcwppbXBvcnQgbG9nZ2luZwppbXBvcnQgdGhyZWFkaW5nCmZyb20gZGF0ZXRp',
    'bWUgaW1wb3J0IGRhdGV0aW1lLCB0aW1lem9uZQpmcm9tIGNvbGxlY3Rpb25zIGltcG9ydCBkZWZhdWx0ZGljdCwgZGVxdWUKCnRyeToKICAgIGltcG9ydCByZXF1ZXN0cwpleGNlcHQgSW1wb3J0RXJyb3I6CiAgICBwcmludCgiW0VSUk9SXSAncmVxdWVzdHMnIHBh',
    'a2V0aSBidWx1bmFtYWTEsS4gTMO8dGZlbiAncGlwIGluc3RhbGwgcmVxdWVzdHMnIMOnYWzEscWfdMSxcsSxbi4iKQogICAgZXhpdCgxKQoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09CiMgIFlhcMSxbGFuZMSxcm1hCiMgPT09PT09PT09PT09PT09PT09PT09',
    'PT09PQoKRU5WX1BBVEggPSByIkM6XFByb2dyYW1EYXRhXHVzZXJfYWN0aXZpdHlfbW9uaXRvclx1c2VyX2FjdGl2aXR5X21vbml0b3IuZW52IgpMT0dfRElSID0gciJDOlxQcm9ncmFtRGF0YVx1c2VyX2FjdGl2aXR5X21vbml0b3JcbG9ncyIKTE9HX0ZJTEUgPSBv',
    'cy5wYXRoLmpvaW4oTE9HX0RJUiwgImFjdGl2aXR5X21vbml0b3IubG9nIikKCiMgTG9nZ2luZyB5YXDEsWxhbmTEsXJtYXPEsQpvcy5tYWtlZGlycyhMT0dfRElSLCBleGlzdF9vaz1UcnVlKQpsb2dnaW5nLmJhc2ljQ29uZmlnKAogICAgbGV2ZWw9bG9nZ2luZy5J',
    'TkZPLAogICAgZm9ybWF0PSJbJShhc2N0aW1lKXNdIFslKGxldmVsbmFtZSlzXSAlKG1lc3NhZ2UpcyIsCiAgICBoYW5kbGVycz1bCiAgICAgICAgbG9nZ2luZy5GaWxlSGFuZGxlcihMT0dfRklMRSwgZW5jb2Rpbmc9InV0Zi04IiksCiAgICAgICAgbG9nZ2luZy5T',
    'dHJlYW1IYW5kbGVyKCkKICAgIF0KKQoKIyBXaW5kb3dzIEV2ZW50IElEJ2xlcmkKRVZFTlRfTE9HT05fU1VDQ0VTUyA9IDQ2MjQKRVZFTlRfTE9HT05fRkFJTEVEID0gNDYyNQpFVkVOVF9MT0dPRkYgPSA0NjM0CkVWRU5UX0FDQ09VTlRfTE9DS0VEID0gNDc0MApF',
    'VkVOVF9QUk9DRVNTX0NSRUFURSA9IDQ2ODgKRVZFTlRfRklMRV9BQ0NFU1MgPSA0NjYzICAjIE9iamVjdCBBY2Nlc3MgKEZpbGUpCkVWRU5UX1JFR0lTVFJZX0FDQ0VTUyA9IDQ2NTcgICMgUmVnaXN0cnkgQWNjZXNzCgojIElQIC0+IHNvbiBoYXRhbMSxIGRlbmVt',
    'ZWxlcmluIHphbWFubGFyxLEKZmFpbF9ldmVudHMgPSBkZWZhdWx0ZGljdChkZXF1ZSkKCgojID09PT09PT09PT09PT09PT09PT09PT09PT0KIyAgWWFyZMSxbWPEsSBGb25rc2l5b25sYXIKIyA9PT09PT09PT09PT09PT09PT09PT09PT09CgpkZWYgbG9hZF9lbnYo',
    'cGF0aDogc3RyKSAtPiBkaWN0OgogICAgIiIiV2luZG93cyAuZW52IGRvc3lhc8SxbsSxIG9rdXIiIiIKICAgIGVudiA9IHt9CiAgICBpZiBub3Qgb3MucGF0aC5leGlzdHMocGF0aCk6CiAgICAgICAgbG9nZ2luZy53YXJuaW5nKGYiW1dBUk5dIEVudiBkb3N5YXPE',
    'sSBidWx1bmFtYWTEsToge3BhdGh9IikKICAgICAgICByZXR1cm4gZW52CgogICAgdHJ5OgogICAgICAgIHdpdGggb3BlbihwYXRoLCAiciIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgICAgIGZvciBsaW5lIGluIGY6CiAgICAgICAgICAgICAgICBs',
    'aW5lID0gbGluZS5zdHJpcCgpCiAgICAgICAgICAgICAgICBpZiBub3QgbGluZSBvciBsaW5lLnN0YXJ0c3dpdGgoIiMiKToKICAgICAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAgICAgaWYgIj0iIG5vdCBpbiBsaW5lOgogICAgICAgICAgICAg',
    'ICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgICAgICBrZXksIHZhbHVlID0gbGluZS5zcGxpdCgiPSIsIDEpCiAgICAgICAgICAgICAgICBrZXkgPSBrZXkuc3RyaXAoKQogICAgICAgICAgICAgICAgdmFsdWUgPSB2YWx1ZS5zdHJpcCgpLnN0cmlwKCciJykuc3Ry',
    'aXAoIiciKQogICAgICAgICAgICAgICAgZW52W2tleV0gPSB2YWx1ZQogICAgICAgIGxvZ2dpbmcuaW5mbyhmIltJTkZPXSBFbnYgZG9zeWFzxLEgecO8a2xlbmRpOiB7cGF0aH0iKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIGxvZ2dpbmcuZXJy',
    'b3IoZiJbRVJST1JdIEVudiBkb3N5YXPEsSBva3VudXJrZW4gaGF0YToge2V9IikKICAgIAogICAgcmV0dXJuIGVudgoKCmRlZiBnZXRfcHJpbWFyeV9pcCgpIC0+IHN0cjoKICAgICIiIldpbmRvd3MndGEgYW5hIElQIGFkcmVzaW5pIGJ1bHVyIiIiCiAgICB0cnk6',
    'CiAgICAgICAgcyA9IHNvY2tldC5zb2NrZXQoc29ja2V0LkFGX0lORVQsIHNvY2tldC5TT0NLX0RHUkFNKQogICAgICAgIHMuY29ubmVjdCgoIjguOC44LjgiLCA4MCkpCiAgICAgICAgaXAgPSBzLmdldHNvY2tuYW1lKClbMF0KICAgICAgICBzLmNsb3NlKCkKICAg',
    'ICAgICByZXR1cm4gaXAKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcmV0dXJuICIxMjcuMC4wLjEiCgoKZGVmIGJhbl9pcF93aW5kb3dzKGlwOiBzdHIsIHNzaF9wb3J0OiBpbnQgPSAyMik6CiAgICAiIiJXaW5kb3dzIEZpcmV3YWxsIGlsZSBJUCd5aSBi',
    'YW5sYXIiIiIKICAgIHRyeToKICAgICAgICBydWxlX25hbWUgPSBmIlNTSF9CQU5fe2lwLnJlcGxhY2UoJy4nLCAnXycpfSIKICAgICAgICBjaGVja19jbWQgPSBbCiAgICAgICAgICAgICJuZXRzaCIsICJhZHZmaXJld2FsbCIsICJmaXJld2FsbCIsICJzaG93Iiwg',
    'InJ1bGUiLAogICAgICAgICAgICBmIm5hbWU9e3J1bGVfbmFtZX0iCiAgICAgICAgXQogICAgICAgIHJlc3VsdCA9IHN1YnByb2Nlc3MucnVuKGNoZWNrX2NtZCwgY2FwdHVyZV9vdXRwdXQ9VHJ1ZSwgdGV4dD1UcnVlLCB0aW1lb3V0PTUpCiAgICAgICAgCiAgICAg',
    'ICAgaWYgIk5vIHJ1bGVzIG1hdGNoIiBpbiByZXN1bHQuc3Rkb3V0IG9yIHJlc3VsdC5yZXR1cm5jb2RlICE9IDA6CiAgICAgICAgICAgIGFkZF9jbWQgPSBbCiAgICAgICAgICAgICAgICAibmV0c2giLCAiYWR2ZmlyZXdhbGwiLCAiZmlyZXdhbGwiLCAiYWRkIiwg',
    'InJ1bGUiLAogICAgICAgICAgICAgICAgZiJuYW1lPXtydWxlX25hbWV9IiwKICAgICAgICAgICAgICAgICJkaXI9aW4iLAogICAgICAgICAgICAgICAgImFjdGlvbj1ibG9jayIsCiAgICAgICAgICAgICAgICBmInJlbW90ZWlwPXtpcH0iLAogICAgICAgICAgICAg',
    'ICAgInByb3RvY29sPXRjcCIsCiAgICAgICAgICAgICAgICBmImxvY2FscG9ydD17c3NoX3BvcnR9IiwKICAgICAgICAgICAgICAgICJlbmFibGU9eWVzIgogICAgICAgICAgICBdCiAgICAgICAgICAgIHN1YnByb2Nlc3MucnVuKGFkZF9jbWQsIGNoZWNrPUZhbHNl',
    'LCBjYXB0dXJlX291dHB1dD1UcnVlLCB0aW1lb3V0PTUpCiAgICAgICAgICAgIGxvZ2dpbmcuaW5mbyhmIltCQU5dIHtpcH0gV2luZG93cyBGaXJld2FsbCBpbGUgYmFubGFuZMSxIikKICAgICAgICAgICAgcmV0dXJuIFRydWUKICAgICAgICByZXR1cm4gRmFsc2UK',
    'ICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICBsb2dnaW5nLmVycm9yKGYiW0VSUk9SXSBJUCBiYW5sYW1hIGhhdGFzxLEgKHtpcH0pOiB7ZX0iKQogICAgICAgIHJldHVybiBGYWxzZQoKCmRlZiBzZW5kX3RvX3dlYmhvb2sod2ViaG9va191cmw6IHN0',
    'ciwgcGF5bG9hZDogZGljdCwgbWF4X3JldHJpZXM6IGludCA9IDMpOgogICAgIiIibjhuIHdlYmhvb2snYSBnw7ZuZGVyaXIsIHJldHJ5IG1la2FuaXptYXPEsSBpbGUiIiIKICAgIGZvciBhdHRlbXB0IGluIHJhbmdlKG1heF9yZXRyaWVzKToKICAgICAgICB0cnk6',
    'CiAgICAgICAgICAgIHIgPSByZXF1ZXN0cy5wb3N0KHdlYmhvb2tfdXJsLCBqc29uPXBheWxvYWQsIHRpbWVvdXQ9NSkKICAgICAgICAgICAgci5yYWlzZV9mb3Jfc3RhdHVzKCkKICAgICAgICAgICAgbG9nZ2luZy5kZWJ1ZyhmIltXRUJIT09LXSBCYcWfYXLEsWzE',
    'sToge3BheWxvYWQuZ2V0KCdldmVudF90eXBlJyl9IikKICAgICAgICAgICAgcmV0dXJuIFRydWUKICAgICAgICBleGNlcHQgcmVxdWVzdHMuZXhjZXB0aW9ucy5SZXF1ZXN0RXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgIGlmIGF0dGVtcHQgPCBtYXhfcmV0cmll',
    'cyAtIDE6CiAgICAgICAgICAgICAgICBsb2dnaW5nLndhcm5pbmcoZiJbV0VCSE9PS10gRGVuZW1lIHthdHRlbXB0ICsgMX0ve21heF9yZXRyaWVzfSBiYcWfYXLEsXPEsXouLi4iKQogICAgICAgICAgICAgICAgdGltZS5zbGVlcCgyKQogICAgICAgICAgICBlbHNl',
    'OgogICAgICAgICAgICAgICAgbG9nZ2luZy5lcnJvcihmIltXRUJIT09LXSB7bWF4X3JldHJpZXN9IGRlbmVtZSBzb25yYXPEsSBiYcWfYXLEsXPEsXo6IHtlfSIpCiAgICAgICAgICAgICAgICBlcnJvcl9sb2cgPSBvcy5wYXRoLmpvaW4oTE9HX0RJUiwgIndlYmhv',
    'b2tfZXJyb3JzLmxvZyIpCiAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgd2l0aCBvcGVuKGVycm9yX2xvZywgImEiLCBlbmNvZGluZz0idXRmLTgiKSBhcyBmOgogICAgICAgICAgICAgICAgICAgICAgICBmLndyaXRlKGpzb24uZHVtcHMo',
    'ewogICAgICAgICAgICAgICAgICAgICAgICAgICAgInRpbWVzdGFtcCI6IGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLmlzb2Zvcm1hdCgpLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgImVycm9yIjogc3RyKGUpLAogICAgICAgICAgICAgICAgICAgICAg',
    'ICAgICAgInBheWxvYWQiOiBwYXlsb2FkCiAgICAgICAgICAgICAgICAgICAgICAgIH0pICsgIlxuIikKICAgICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAgICAgICAgcmV0dXJuIEZhbHNlCiAg',
    'ICByZXR1cm4gRmFsc2UKCgpkZWYgdHJhY2tfZmFpbF9hbmRfY2hlY2tfYmFuKGlwOiBzdHIsIG5vd190czogZmxvYXQsIHRpbWVfd2luZG93OiBpbnQsIG1heF9hdHRlbXB0czogaW50KToKICAgICIiIkJhxZ9hcsSxc8SxeiBkZW5lbWVsZXJpIHRha2lwIGVkZXIg',
    'dmUgYmFuIGtvbnRyb2zDvCB5YXBhciIiIgogICAgZHEgPSBmYWlsX2V2ZW50c1tpcF0KICAgIGRxLmFwcGVuZChub3dfdHMpCiAgICAKICAgIGN1dG9mZiA9IG5vd190cyAtIHRpbWVfd2luZG93CiAgICB3aGlsZSBkcSBhbmQgZHFbMF0gPCBjdXRvZmY6CiAgICAg',
    'ICAgZHEucG9wbGVmdCgpCiAgICAKICAgIGZhaWxfY291bnQgPSBsZW4oZHEpCiAgICBiYW5fdHJpZ2dlcmVkID0gZmFpbF9jb3VudCA+PSBtYXhfYXR0ZW1wdHMKICAgIHJldHVybiBmYWlsX2NvdW50LCBiYW5fdHJpZ2dlcmVkCgoKZGVmIHJlYWRfd2luZG93c19l',
    'dmVudHMobG9nX25hbWU6IHN0ciwgZXZlbnRfaWRzOiBsaXN0LCBtYXhfZXZlbnRzOiBpbnQgPSAxMDApOgogICAgIiIiUG93ZXJTaGVsbCBpbGUgV2luZG93cyBFdmVudCBMb2cnZGFuIGV2ZW50bGVyaSBva3VyIiIiCiAgICBldmVudF9pZHNfc3RyID0gIiwiLmpv',
    'aW4obWFwKHN0ciwgZXZlbnRfaWRzKSkKICAgICMgUG93ZXJTaGVsbCBzY3JpcHQgLSAkIGthcmFrdGVybGVyaW5pIGVzY2FwZSBldG1layBpw6dpbiBiYWNrdGljayBrdWxsYW4KICAgIHBzX3RlbXBsYXRlID0gJ0dldC1XaW5FdmVudCAtTG9nTmFtZSAie2xvZ19u',
    'YW1lfSIgLU1heEV2ZW50cyB7bWF4X2V2ZW50c30gLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUgfCBXaGVyZS1PYmplY3Qge3sgYCRfLklkIC1pbiBAKHtldmVudF9pZHNfc3RyfSkgfX0gfCBGb3JFYWNoLU9iamVjdCB7eyBgJHRpbWUgPSBgJF8uVGltZUNy',
    'ZWF0ZWQuVG9TdHJpbmcoInl5eXktTU0tZGQgSEg6bW06c3MiKTsgYCRpZCA9IGAkXy5JZDsgYCRtc2cgPSBgJF8uTWVzc2FnZTsgYCR4bWwgPSBgJF8uVG9YbWwoKTsgV3JpdGUtT3V0cHV0ICJgJHRpbWV8YCRpZHxgJHhtbHxgJG1zZyIgfX0nCiAgICBwc19zY3Jp',
    'cHQgPSBwc190ZW1wbGF0ZS5mb3JtYXQobG9nX25hbWU9bG9nX25hbWUsIG1heF9ldmVudHM9bWF4X2V2ZW50cywgZXZlbnRfaWRzX3N0cj1ldmVudF9pZHNfc3RyKQogICAgCiAgICB0cnk6CiAgICAgICAgcmVzdWx0ID0gc3VicHJvY2Vzcy5ydW4oCiAgICAgICAg',
    'ICAgIFsicG93ZXJzaGVsbCIsICItQ29tbWFuZCIsIHBzX3NjcmlwdF0sCiAgICAgICAgICAgIGNhcHR1cmVfb3V0cHV0PVRydWUsCiAgICAgICAgICAgIHRleHQ9VHJ1ZSwKICAgICAgICAgICAgdGltZW91dD0xMAogICAgICAgICkKICAgICAgICByZXR1cm4gcmVz',
    'dWx0LnN0ZG91dAogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIGxvZ2dpbmcuZXJyb3IoZiJbRVJST1JdIFBvd2VyU2hlbGwgZXZlbnQgb2t1bWEgaGF0YXPEsToge2V9IikKICAgICAgICByZXR1cm4gIiIKCgpkZWYgcGFyc2VfZXZlbnRfeG1sKHht',
    'bF9zdHI6IHN0cik6CiAgICAiIiJFdmVudCBYTUwnZGVuIGJpbGdpbGVyaSDDp8Sxa2FyxLFyIiIiCiAgICBkYXRhID0ge30KICAgIHRyeToKICAgICAgICAjIEJhc2l0IFhNTCBwYXJzaW5nIChFdmVudERhdGEgacOnaW5kZWtpIERhdGEgZWxlbWVudGxlcmkpCiAg',
    'ICAgICAgaW1wb3J0IHhtbC5ldHJlZS5FbGVtZW50VHJlZSBhcyBFVAogICAgICAgIHJvb3QgPSBFVC5mcm9tc3RyaW5nKHhtbF9zdHIpCiAgICAgICAgCiAgICAgICAgIyBFdmVudERhdGEgacOnaW5kZWtpIERhdGEgZWxlbWVudGxlcmluaSBidWwKICAgICAgICBm',
    'b3IgZGF0YV9lbGVtIGluIHJvb3QuZmluZGFsbCgiLi8ve2h0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd2luLzIwMDQvMDgvZXZlbnRzL2V2ZW50fURhdGEiKToKICAgICAgICAgICAgbmFtZSA9IGRhdGFfZWxlbS5nZXQoIk5hbWUiLCAiIikKICAgICAgICAg',
    'ICAgdmFsdWUgPSBkYXRhX2VsZW0udGV4dCBvciAiIgogICAgICAgICAgICBpZiBuYW1lOgogICAgICAgICAgICAgICAgZGF0YVtuYW1lLmxvd2VyKCldID0gdmFsdWUKICAgICAgICAKICAgICAgICAjIFN5c3RlbSBpw6dpbmRla2kgYmlsZ2lsZXIKICAgICAgICBz',
    'eXN0ZW0gPSByb290LmZpbmQoIi4vL3todHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dpbi8yMDA0LzA4L2V2ZW50cy9ldmVudH1TeXN0ZW0iKQogICAgICAgIGlmIHN5c3RlbSBpcyBub3QgTm9uZToKICAgICAgICAgICAgZXZlbnRfaWRfZWxlbSA9IHN5c3Rl',
    'bS5maW5kKCIuLy97aHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93aW4vMjAwNC8wOC9ldmVudHMvZXZlbnR9RXZlbnRJRCIpCiAgICAgICAgICAgIGlmIGV2ZW50X2lkX2VsZW0gaXMgbm90IE5vbmU6CiAgICAgICAgICAgICAgICBkYXRhWyJldmVudF9pZCJd',
    'ID0gZXZlbnRfaWRfZWxlbS50ZXh0CiAgICAgICAgCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgbG9nZ2luZy5kZWJ1ZyhmIltERUJVR10gWE1MIHBhcnNlIGhhdGFzxLE6IHtlfSIpCiAgICAKICAgIHJldHVybiBkYXRhCgoKZGVmIGdldF9wb3dl',
    'cnNoZWxsX2hpc3RvcnkodXNlcjogc3RyID0gTm9uZSk6CiAgICAiIiJQb3dlclNoZWxsIGtvbXV0IGdlw6dtacWfaW5pIG9rdXIiIiIKICAgIGhpc3RvcnlfcGF0aHMgPSBbCiAgICAgICAgciJDOlxVc2Vyc1x7fVxBcHBEYXRhXFJvYW1pbmdcTWljcm9zb2Z0XFdp',
    'bmRvd3NcUG93ZXJTaGVsbFxQU1JlYWRMaW5lXENvbnNvbGVIb3N0X2hpc3RvcnkudHh0Ii5mb3JtYXQodXNlciBvciBvcy5nZXRlbnYoIlVTRVJOQU1FIikpLAogICAgICAgIHIiQzpcVXNlcnNce31cQXBwRGF0YVxSb2FtaW5nXE1pY3Jvc29mdFxXaW5kb3dzXFBv',
    'd2VyU2hlbGxcUFNSZWFkTGluZVxDb25zb2xlSG9zdF9oaXN0b3J5LnR4dCIuZm9ybWF0KG9zLmdldGVudigiVVNFUk5BTUUiKSkKICAgIF0KICAgIAogICAgY29tbWFuZHMgPSBbXQogICAgZm9yIGhpc3RfcGF0aCBpbiBoaXN0b3J5X3BhdGhzOgogICAgICAgIGlm',
    'IG9zLnBhdGguZXhpc3RzKGhpc3RfcGF0aCk6CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHdpdGggb3BlbihoaXN0X3BhdGgsICJyIiwgZW5jb2Rpbmc9InV0Zi04IiwgZXJyb3JzPSJpZ25vcmUiKSBhcyBmOgogICAgICAgICAgICAgICAgICAgIGxp',
    'bmVzID0gZi5yZWFkbGluZXMoKQogICAgICAgICAgICAgICAgICAgIGNvbW1hbmRzLmV4dGVuZChsaW5lc1stMTA6XSkKICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgICAgIHBhc3MKICAgIAogICAgcmV0dXJuIGNvbW1hbmRzWy0xMDpd',
    'IGlmIGNvbW1hbmRzIGVsc2UgW10KCgpkZWYgbW9uaXRvcl9wb3dlcnNoZWxsX2hpc3RvcnkoKToKICAgICIiIlBvd2VyU2hlbGwga29tdXQgZ2XDp21pxZ9pbmkgcGVyaXlvZGlrIG9sYXJhayBrb250cm9sIGVkZXIiIiIKICAgIGxhc3RfY2hlY2tzID0ge30KICAg',
    'IAogICAgd2hpbGUgVHJ1ZToKICAgICAgICB0cnk6CiAgICAgICAgICAgICMgVMO8bSBrdWxsYW7EsWPEsWxhcsSxbiBoaXN0b3J5IGRvc3lhbGFyxLFuxLEga29udHJvbCBldAogICAgICAgICAgICB1c2Vyc19kaXIgPSByIkM6XFVzZXJzIgogICAgICAgICAgICBp',
    'ZiBvcy5wYXRoLmV4aXN0cyh1c2Vyc19kaXIpOgogICAgICAgICAgICAgICAgZm9yIHVzZXJfZGlyIGluIG9zLmxpc3RkaXIodXNlcnNfZGlyKToKICAgICAgICAgICAgICAgICAgICB1c2VyX3BhdGggPSBvcy5wYXRoLmpvaW4odXNlcnNfZGlyLCB1c2VyX2RpcikK',
    'ICAgICAgICAgICAgICAgICAgICBpZiBvcy5wYXRoLmlzZGlyKHVzZXJfcGF0aCk6CiAgICAgICAgICAgICAgICAgICAgICAgIGhpc3RfZmlsZSA9IG9zLnBhdGguam9pbigKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHVzZXJfcGF0aCwKICAgICAgICAgICAg',
    'ICAgICAgICAgICAgICAgIHIiQXBwRGF0YVxSb2FtaW5nXE1pY3Jvc29mdFxXaW5kb3dzXFBvd2VyU2hlbGxcUFNSZWFkTGluZVxDb25zb2xlSG9zdF9oaXN0b3J5LnR4dCIKICAgICAgICAgICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAgICAgICAgICBp',
    'ZiBvcy5wYXRoLmV4aXN0cyhoaXN0X2ZpbGUpOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgbXRpbWUgPSBvcy5wYXRoLmdldG10aW1lKGhpc3RfZmlsZSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGxhc3RfY2hlY2sgPSBsYXN0X2NoZWNrcy5nZXQo',
    'aGlzdF9maWxlLCAwKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBpZiBtdGltZSA+IGxhc3RfY2hlY2s6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIyBZZW5pIGtvbXV0bGFyIHZhcgogICAg',
    'ICAgICAgICAgICAgICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgd2l0aCBvcGVuKGhpc3RfZmlsZSwgInIiLCBlbmNvZGluZz0idXRmLTgiLCBlcnJvcnM9Imlnbm9yZSIpIGFzIGY6CiAgICAgICAgICAgICAg',
    'ICAgICAgICAgICAgICAgICAgICAgICAgICBsaW5lcyA9IGYucmVhZGxpbmVzKCkKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIG5ld19jb21tYW5kcyA9IGxpbmVzWy01Ol0gICMgU29uIDUga29tdXQKICAgICAgICAgICAgICAgICAgICAg',
    'ICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZm9yIGNtZCBpbiBuZXdfY29tbWFuZHM6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgbG9nZ2luZy5pbmZvKGYiW1BPV0VS',
    'U0hFTExdIHt1c2VyX2Rpcn06IHtjbWQuc3RyaXAoKX0iKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHBhc3MKICAgICAgICAgICAgICAgICAgICAgICAg',
    'ICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBsYXN0X2NoZWNrc1toaXN0X2ZpbGVdID0gbXRpbWUKICAgICAgICAgICAgCiAgICAgICAgICAgIHRpbWUuc2xlZXAoMzApICAjIDMwIHNhbml5ZWRlIGJpciBrb250cm9sIGV0CiAgICAgICAg',
    'ICAgIAogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgbG9nZ2luZy5lcnJvcihmIltFUlJPUl0gUG93ZXJTaGVsbCBoaXN0b3J5IGl6bGVtZSBoYXRhc8SxOiB7ZX0iKQogICAgICAgICAgICB0aW1lLnNsZWVwKDYwKQoKCmRlZiBmb2xs',
    'b3dfd2luZG93c19ldmVudHMoKToKICAgICIiIldpbmRvd3MgRXZlbnQgTG9nJ2xhcsSxbsSxIHPDvHJla2xpIGl6bGVyIiIiCiAgICBsYXN0X2V2ZW50X3RpbWVzID0gewogICAgICAgICJTZWN1cml0eSI6IGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLAogICAg',
    'ICAgICJPcGVuU1NIL09wZXJhdGlvbmFsIjogZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0YykKICAgIH0KICAgIAogICAgIyDEsHpsZW5lY2VrIGV2ZW50IElEJ2xlcmkKICAgIHNlY3VyaXR5X2V2ZW50cyA9IFsKICAgICAgICBFVkVOVF9MT0dPTl9TVUNDRVNTLAog',
    'ICAgICAgIEVWRU5UX0xPR09OX0ZBSUxFRCwKICAgICAgICBFVkVOVF9MT0dPRkYsCiAgICAgICAgRVZFTlRfUFJPQ0VTU19DUkVBVEUsCiAgICAgICAgRVZFTlRfRklMRV9BQ0NFU1MsCiAgICAgICAgRVZFTlRfUkVHSVNUUllfQUNDRVNTCiAgICBdCiAgICAKICAg',
    'IHNzaF9ldmVudHMgPSBbNCwgNSwgNl0gICMgT3BlblNTSCBldmVudCBJRCdsZXJpCiAgICAKICAgIHdoaWxlIFRydWU6CiAgICAgICAgdHJ5OgogICAgICAgICAgICAjIFNlY3VyaXR5IExvZwogICAgICAgICAgICBldmVudHMgPSByZWFkX3dpbmRvd3NfZXZlbnRz',
    'KCJTZWN1cml0eSIsIHNlY3VyaXR5X2V2ZW50cywgNTApCiAgICAgICAgICAgIGZvciBsaW5lIGluIGV2ZW50cy5zdHJpcCgpLnNwbGl0KCJcbiIpOgogICAgICAgICAgICAgICAgaWYgbm90IGxpbmUgb3IgInwiIG5vdCBpbiBsaW5lOgogICAgICAgICAgICAgICAg',
    'ICAgIGNvbnRpbnVlCiAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICBwYXJ0cyA9IGxpbmUuc3BsaXQoInwiLCAzKQogICAgICAgICAgICAgICAgICAgIGlmIGxlbihwYXJ0cykgPCA0OgogICAgICAgICAgICAg',
    'ICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgIGV2ZW50X3RpbWVfc3RyLCBldmVudF9pZCwgeG1sX2RhdGEsIG1lc3NhZ2UgPSBwYXJ0cwogICAgICAgICAgICAgICAgICAgIGV2ZW50X3RpbWUgPSBkYXRl',
    'dGltZS5zdHJwdGltZShldmVudF90aW1lX3N0ciwgIiVZLSVtLSVkICVIOiVNOiVTIikKICAgICAgICAgICAgICAgICAgICBldmVudF90aW1lID0gZXZlbnRfdGltZS5yZXBsYWNlKHR6aW5mbz10aW1lem9uZS51dGMpCiAgICAgICAgICAgICAgICAgICAgCiAgICAg',
    'ICAgICAgICAgICAgICAgaWYgZXZlbnRfdGltZSA+IGxhc3RfZXZlbnRfdGltZXNbIlNlY3VyaXR5Il06CiAgICAgICAgICAgICAgICAgICAgICAgIGV2ZW50X2RhdGEgPSBwYXJzZV9ldmVudF94bWwoeG1sX2RhdGEpCiAgICAgICAgICAgICAgICAgICAgICAgIGV2',
    'ZW50X2RhdGFbImV2ZW50X2lkIl0gPSBldmVudF9pZAogICAgICAgICAgICAgICAgICAgICAgICBldmVudF9kYXRhWyJ0aW1lIl0gPSBldmVudF90aW1lCiAgICAgICAgICAgICAgICAgICAgICAgIGV2ZW50X2RhdGFbIm1lc3NhZ2UiXSA9IG1lc3NhZ2UKICAgICAg',
    'ICAgICAgICAgICAgICAgICAgZXZlbnRfZGF0YVsibG9nX25hbWUiXSA9ICJTZWN1cml0eSIKICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgIHlpZWxkIGV2ZW50X2RhdGEKICAgICAgICAgICAgICAgICAgICAgICAgbGFzdF9l',
    'dmVudF90aW1lc1siU2VjdXJpdHkiXSA9IGV2ZW50X3RpbWUKICAgICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgICAgICAgICBsb2dnaW5nLmRlYnVnKGYiW0RFQlVHXSBFdmVudCBwYXJzZSBoYXRhc8SxOiB7ZX0iKQogICAg',
    'ICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIAogICAgICAgICAgICAjIE9wZW5TU0ggTG9nCiAgICAgICAgICAgIGV2ZW50cyA9IHJlYWRfd2luZG93c19ldmVudHMoIk9wZW5TU0gvT3BlcmF0aW9uYWwiLCBzc2hfZXZlbnRzLCA1MCkKICAgICAg',
    'ICAgICAgZm9yIGxpbmUgaW4gZXZlbnRzLnN0cmlwKCkuc3BsaXQoIlxuIik6CiAgICAgICAgICAgICAgICBpZiBub3QgbGluZSBvciAifCIgbm90IGluIGxpbmU6CiAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgIAogICAgICAgICAg',
    'ICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgIHBhcnRzID0gbGluZS5zcGxpdCgifCIsIDMpCiAgICAgICAgICAgICAgICAgICAgaWYgbGVuKHBhcnRzKSA8IDQ6CiAgICAgICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgICAgICAgICAg',
    'CiAgICAgICAgICAgICAgICAgICAgZXZlbnRfdGltZV9zdHIsIGV2ZW50X2lkLCB4bWxfZGF0YSwgbWVzc2FnZSA9IHBhcnRzCiAgICAgICAgICAgICAgICAgICAgZXZlbnRfdGltZSA9IGRhdGV0aW1lLnN0cnB0aW1lKGV2ZW50X3RpbWVfc3RyLCAiJVktJW0tJWQg',
    'JUg6JU06JVMiKQogICAgICAgICAgICAgICAgICAgIGV2ZW50X3RpbWUgPSBldmVudF90aW1lLnJlcGxhY2UodHppbmZvPXRpbWV6b25lLnV0YykKICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICBpZiBldmVudF90aW1lID4gbGFzdF9ldmVu',
    'dF90aW1lc1siT3BlblNTSC9PcGVyYXRpb25hbCJdOgogICAgICAgICAgICAgICAgICAgICAgICBldmVudF9kYXRhID0gcGFyc2VfZXZlbnRfeG1sKHhtbF9kYXRhKQogICAgICAgICAgICAgICAgICAgICAgICBldmVudF9kYXRhWyJldmVudF9pZCJdID0gZXZlbnRf',
    'aWQKICAgICAgICAgICAgICAgICAgICAgICAgZXZlbnRfZGF0YVsidGltZSJdID0gZXZlbnRfdGltZQogICAgICAgICAgICAgICAgICAgICAgICBldmVudF9kYXRhWyJtZXNzYWdlIl0gPSBtZXNzYWdlCiAgICAgICAgICAgICAgICAgICAgICAgIGV2ZW50X2RhdGFb',
    'ImxvZ19uYW1lIl0gPSAiT3BlblNTSC9PcGVyYXRpb25hbCIKICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgIHlpZWxkIGV2ZW50X2RhdGEKICAgICAgICAgICAgICAgICAgICAgICAgbGFzdF9ldmVudF90aW1lc1siT3BlblNT',
    'SC9PcGVyYXRpb25hbCJdID0gZXZlbnRfdGltZQogICAgICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICAgICAgICAgIGxvZ2dpbmcuZGVidWcoZiJbREVCVUddIFNTSCBldmVudCBwYXJzZSBoYXRhc8SxOiB7ZX0iKQogICAgICAg',
    'ICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIAogICAgICAgICAgICB0aW1lLnNsZWVwKDUpICAjIDUgc2FuaXllZGUgYmlyIGtvbnRyb2wgZXQKICAgICAgICAgICAgCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICBsb2dn',
    'aW5nLmVycm9yKGYiW0VSUk9SXSBFdmVudCBpemxlbWUgaGF0YXPEsToge2V9IikKICAgICAgICAgICAgdGltZS5zbGVlcCgxMCkKCgojID09PT09PT09PT09PT09PT09PT09PT09PT0KIyAgQW5hIEZvbmtzaXlvbgojID09PT09PT09PT09PT09PT09PT09PT09PT0K',
    'CmRlZiBtYWluKCk6CiAgICAiIiJBbmEgZMO2bmfDvCIiIgogICAgbG9nZ2luZy5pbmZvKCI9IiAqIDYwKQogICAgbG9nZ2luZy5pbmZvKCJLdWxsYW7EsWPEsSBBa3Rpdml0ZSDEsHpsZW1lIFNpc3RlbWkgLSBXaW5kb3dzIFNlcnZlciIpCiAgICBsb2dnaW5nLmlu',
    'Zm8oIj0iICogNjApCiAgICAKICAgICMgLmVudiBkb3N5YXPEsW7EsSB5w7xrbGUKICAgIGVudiA9IGxvYWRfZW52KEVOVl9QQVRIKQogICAgCiAgICAjIEdlcmVrbGkgYXlhcmxhcsSxIGtvbnRyb2wgZXQKICAgIHdlYmhvb2tfdXJsID0gZW52LmdldCgiV0VCSE9P',
    'S19VUkwiLCAiIikuc3RyaXAoKQogICAgaWYgbm90IHdlYmhvb2tfdXJsOgogICAgICAgIGxvZ2dpbmcuZXJyb3IoIltGQVRBTF0gV0VCSE9PS19VUkwgLmVudiBkb3N5YXPEsW5kYSB0YW7EsW1sxLEgZGXEn2lsISIpCiAgICAgICAgbG9nZ2luZy5lcnJvcihmIltG',
    'QVRBTF0gTMO8dGZlbiB7RU5WX1BBVEh9IGRvc3lhc8SxbsSxIGTDvHplbmxleWluLiIpCiAgICAgICAgcmV0dXJuCiAgICAKICAgICMgU3VudWN1IGJpbGdpbGVyaQogICAgaG9zdG5hbWUgPSBzb2NrZXQuZ2V0aG9zdG5hbWUoKQogICAgcHJpbWFyeV9pcCA9IGdl',
    'dF9wcmltYXJ5X2lwKCkKICAgIHNlcnZlcl9uYW1lID0gZW52LmdldCgiU0VSVkVSX05BTUUiLCAiIikuc3RyaXAoKSBvciBob3N0bmFtZQogICAgc2VydmVyX2lwID0gZW52LmdldCgiU0VSVkVSX0lQIiwgIiIpLnN0cmlwKCkgb3IgcHJpbWFyeV9pcAogICAgc2Vy',
    'dmVyX2VudiA9IGVudi5nZXQoIlNFUlZFUl9FTlYiLCAiUHJvZHVjdGlvbiIpCiAgICAKICAgICMgR8O8dmVubGlrIGF5YXJsYXLEsQogICAgbWF4X2F0dGVtcHRzID0gaW50KGVudi5nZXQoIk1BWF9BVFRFTVBUUyIsICI1IikpCiAgICB0aW1lX3dpbmRvd19zZWMg',
    'PSBpbnQoZW52LmdldCgiVElNRV9XSU5ET1dfU0VDIiwgIjEyMCIpKQogICAgYmFuX2R1cmF0aW9uID0gaW50KGVudi5nZXQoIkJBTl9EVVJBVElPTiIsICIzNjAwIikpCiAgICBhbGVydF9vbl9zdWNjZXNzID0gZW52LmdldCgiQUxFUlRfT05fU1VDQ0VTUyIsICIx',
    'IikgaW4gKCIxIiwgInRydWUiLCAiVHJ1ZSIsICJZRVMiLCAieWVzIikKICAgIAogICAgIyDEsHpsZW1lIGF5YXJsYXLEsQogICAgbW9uaXRvcl9jb21tYW5kcyA9IGVudi5nZXQoIk1PTklUT1JfQ09NTUFORFMiLCAiMSIpIGluICgiMSIsICJ0cnVlIiwgIlRydWUi',
    'LCAiWUVTIiwgInllcyIpCiAgICBtb25pdG9yX3Byb2Nlc3NlcyA9IGVudi5nZXQoIk1PTklUT1JfUFJPQ0VTU0VTIiwgIjEiKSBpbiAoIjEiLCAidHJ1ZSIsICJUcnVlIiwgIllFUyIsICJ5ZXMiKQogICAgbW9uaXRvcl9sb2dpbnMgPSBlbnYuZ2V0KCJNT05JVE9S',
    'X0xPR0lOUyIsICIxIikgaW4gKCIxIiwgInRydWUiLCAiVHJ1ZSIsICJZRVMiLCAieWVzIikKICAgIG1vbml0b3JfZmlsZV9hY2Nlc3MgPSBlbnYuZ2V0KCJNT05JVE9SX0ZJTEVfQUNDRVNTIiwgIjAiKSBpbiAoIjEiLCAidHJ1ZSIsICJUcnVlIiwgIllFUyIsICJ5',
    'ZXMiKQogICAgCiAgICAjIFdoaXRlbGlzdAogICAgd2hpdGVsaXN0X2lwcyA9IFtdCiAgICB3aGl0ZWxpc3Rfc3RyID0gZW52LmdldCgiV0hJVEVMSVNUX0lQUyIsICIiKS5zdHJpcCgpCiAgICBpZiB3aGl0ZWxpc3Rfc3RyOgogICAgICAgIHdoaXRlbGlzdF9pcHMg',
    'PSBbaXAuc3RyaXAoKSBmb3IgaXAgaW4gd2hpdGVsaXN0X3N0ci5zcGxpdCgiLCIpIGlmIGlwLnN0cmlwKCldCiAgICAKICAgIGxvZ2dpbmcuaW5mbyhmIltJTkZPXSBXZWJob29rIFVSTDoge3dlYmhvb2tfdXJsfSIpCiAgICBsb2dnaW5nLmluZm8oZiJbSU5GT10g',
    'U3VudWN1OiB7c2VydmVyX25hbWV9ICh7c2VydmVyX2lwfSkgfCBPcnRhbToge3NlcnZlcl9lbnZ9IikKICAgIGxvZ2dpbmcuaW5mbyhmIltJTkZPXSBFxZ9pazoge21heF9hdHRlbXB0c30gZGVuZW1lIC8ge3RpbWVfd2luZG93X3NlY30gc2FuaXllIikKICAgIGxv',
    'Z2dpbmcuaW5mbyhmIltJTkZPXSDEsHpsZW1lOiBLb211dGxhcj17bW9uaXRvcl9jb21tYW5kc30sIFByb2Nlc3M9e21vbml0b3JfcHJvY2Vzc2VzfSwgTG9naW49e21vbml0b3JfbG9naW5zfSIpCiAgICAKICAgICMgUG93ZXJTaGVsbCBoaXN0b3J5IGl6bGVtZSB0',
    'aHJlYWQnaSBiYcWfbGF0CiAgICBpZiBtb25pdG9yX2NvbW1hbmRzOgogICAgICAgIGhpc3RvcnlfdGhyZWFkID0gdGhyZWFkaW5nLlRocmVhZCh0YXJnZXQ9bW9uaXRvcl9wb3dlcnNoZWxsX2hpc3RvcnksIGRhZW1vbj1UcnVlKQogICAgICAgIGhpc3RvcnlfdGhy',
    'ZWFkLnN0YXJ0KCkKICAgICAgICBsb2dnaW5nLmluZm8oIltJTkZPXSBQb3dlclNoZWxsIGtvbXV0IGdlw6dtacWfaSBpemxlbWUgYmHFn2xhdMSxbGTEsSIpCiAgICAKICAgICMgRXZlbnQgTG9nIGl6bGVtZQogICAgbG9nZ2luZy5pbmZvKCJbSU5GT10gV2luZG93',
    'cyBFdmVudCBMb2cgaXpsZW1lIGJhxZ9sYXTEsWzEsXlvci4uLiIpCiAgICAKICAgIHRyeToKICAgICAgICBmb3IgZXZlbnQgaW4gZm9sbG93X3dpbmRvd3NfZXZlbnRzKCk6CiAgICAgICAgICAgIGV2ZW50X2lkID0gaW50KGV2ZW50LmdldCgiZXZlbnRfaWQiLCAw',
    'KSkKICAgICAgICAgICAgZXZlbnRfdGltZSA9IGV2ZW50LmdldCgidGltZSIsIGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpKQogICAgICAgICAgICBtZXNzYWdlID0gZXZlbnQuZ2V0KCJtZXNzYWdlIiwgIiIpCiAgICAgICAgICAgIAogICAgICAgICAgICAjIEJh',
    'c2UgcGF5bG9hZAogICAgICAgICAgICBiYXNlX3BheWxvYWQgPSB7CiAgICAgICAgICAgICAgICAidGltZXN0YW1wIjogZXZlbnRfdGltZS5pc29mb3JtYXQoKSwKICAgICAgICAgICAgICAgICJzZXJ2aWNlIjogInVzZXJfYWN0aXZpdHkiLAogICAgICAgICAgICAg',
    'ICAgInNlcnZlcl9uYW1lIjogc2VydmVyX25hbWUsCiAgICAgICAgICAgICAgICAic2VydmVyX2lwIjogc2VydmVyX2lwLAogICAgICAgICAgICAgICAgInNlcnZlcl9lbnYiOiBzZXJ2ZXJfZW52LAogICAgICAgICAgICAgICAgImV2ZW50X2lkIjogZXZlbnRfaWQs',
    'CiAgICAgICAgICAgICAgICAicmF3X2xvZyI6IG1lc3NhZ2UKICAgICAgICAgICAgfQogICAgICAgICAgICAKICAgICAgICAgICAgbm93X3RzID0gZXZlbnRfdGltZS50aW1lc3RhbXAoKQogICAgICAgICAgICAKICAgICAgICAgICAgIyBMb2dvbiBTdWNjZXNzICg0',
    'NjI0KQogICAgICAgICAgICBpZiBldmVudF9pZCA9PSBFVkVOVF9MT0dPTl9TVUNDRVNTOgogICAgICAgICAgICAgICAgaWYgbm90IG1vbml0b3JfbG9naW5zOgogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgICAgICAKICAgICAgICAgICAg',
    'ICAgIHVzZXJuYW1lID0gZXZlbnQuZ2V0KCJ0YXJnZXR1c2VybmFtZSIsIGV2ZW50LmdldCgic3ViamVjdHVzZXJuYW1lIiwgIiIpKQogICAgICAgICAgICAgICAgaXAgPSBldmVudC5nZXQoImlwYWRkcmVzcyIsIGV2ZW50LmdldCgiaXAiLCAiIikpCiAgICAgICAg',
    'ICAgICAgICBsb2dvbl90eXBlID0gZXZlbnQuZ2V0KCJsb2dvbnR5cGUiLCAiIikKICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgaWYgYWxlcnRfb25fc3VjY2VzcyBhbmQgaXAgYW5kIGlwIG5vdCBpbiB3aGl0ZWxpc3RfaXBzOgogICAgICAgICAgICAg',
    'ICAgICAgIGJhc2VfcGF5bG9hZC51cGRhdGUoewogICAgICAgICAgICAgICAgICAgICAgICAiZXZlbnRfdHlwZSI6ICJsb2dvbl9zdWNjZXNzIiwKICAgICAgICAgICAgICAgICAgICAgICAgInVzZXIiOiB1c2VybmFtZSwKICAgICAgICAgICAgICAgICAgICAgICAg',
    'ImlwIjogaXAsCiAgICAgICAgICAgICAgICAgICAgICAgICJsb2dvbl90eXBlIjogbG9nb25fdHlwZQogICAgICAgICAgICAgICAgICAgIH0pCiAgICAgICAgICAgICAgICAgICAgc2VuZF90b193ZWJob29rKHdlYmhvb2tfdXJsLCBiYXNlX3BheWxvYWQpCiAgICAg',
    'ICAgICAgICAgICAgICAgbG9nZ2luZy5pbmZvKGYiW0xPR09OXSB7dXNlcm5hbWV9IEAge2lwfSIpCiAgICAgICAgICAgIAogICAgICAgICAgICAjIExvZ29uIEZhaWxlZCAoNDYyNSkKICAgICAgICAgICAgZWxpZiBldmVudF9pZCA9PSBFVkVOVF9MT0dPTl9GQUlM',
    'RUQ6CiAgICAgICAgICAgICAgICBpZiBub3QgbW9uaXRvcl9sb2dpbnM6CiAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgdXNlcm5hbWUgPSBldmVudC5nZXQoInRhcmdldHVzZXJuYW1lIiwgZXZlbnQu',
    'Z2V0KCJzdWJqZWN0dXNlcm5hbWUiLCAiIikpCiAgICAgICAgICAgICAgICBpcCA9IGV2ZW50LmdldCgiaXBhZGRyZXNzIiwgZXZlbnQuZ2V0KCJpcCIsICIiKSkKICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgaWYgaXAgYW5kIGlwIG5vdCBpbiB3aGl0',
    'ZWxpc3RfaXBzOgogICAgICAgICAgICAgICAgICAgIGZhaWxfY291bnQsIGJhbl90cmlnZ2VyZWQgPSB0cmFja19mYWlsX2FuZF9jaGVja19iYW4oCiAgICAgICAgICAgICAgICAgICAgICAgIGlwLCBub3dfdHMsIHRpbWVfd2luZG93X3NlYywgbWF4X2F0dGVtcHRz',
    'CiAgICAgICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgIGlmIGJhbl90cmlnZ2VyZWQ6CiAgICAgICAgICAgICAgICAgICAgICAgIGJhbl9pcF93aW5kb3dzKGlwKQogICAgICAgICAgICAgICAgICAgIAogICAg',
    'ICAgICAgICAgICAgICAgIGJhc2VfcGF5bG9hZC51cGRhdGUoewogICAgICAgICAgICAgICAgICAgICAgICAiZXZlbnRfdHlwZSI6ICJsb2dvbl9mYWlsZWQiLAogICAgICAgICAgICAgICAgICAgICAgICAidXNlciI6IHVzZXJuYW1lLAogICAgICAgICAgICAgICAg',
    'ICAgICAgICAiaXAiOiBpcCwKICAgICAgICAgICAgICAgICAgICAgICAgImZhaWxfY291bnRfd2luZG93IjogZmFpbF9jb3VudCwKICAgICAgICAgICAgICAgICAgICAgICAgImJhbl90cmlnZ2VyZWQiOiBiYW5fdHJpZ2dlcmVkCiAgICAgICAgICAgICAgICAgICAg',
    'fSkKICAgICAgICAgICAgICAgICAgICBzZW5kX3RvX3dlYmhvb2sod2ViaG9va191cmwsIGJhc2VfcGF5bG9hZCkKICAgICAgICAgICAgICAgICAgICBsb2dnaW5nLndhcm5pbmcoZiJbTE9HT04gRkFJTEVEXSB7dXNlcm5hbWV9IEAge2lwfSIpCiAgICAgICAgICAg',
    'IAogICAgICAgICAgICAjIExvZ29mZiAoNDYzNCkKICAgICAgICAgICAgZWxpZiBldmVudF9pZCA9PSBFVkVOVF9MT0dPRkY6CiAgICAgICAgICAgICAgICBpZiBtb25pdG9yX2xvZ2luczoKICAgICAgICAgICAgICAgICAgICB1c2VybmFtZSA9IGV2ZW50LmdldCgi',
    'dGFyZ2V0dXNlcm5hbWUiLCBldmVudC5nZXQoInN1YmplY3R1c2VybmFtZSIsICIiKSkKICAgICAgICAgICAgICAgICAgICBiYXNlX3BheWxvYWQudXBkYXRlKHsKICAgICAgICAgICAgICAgICAgICAgICAgImV2ZW50X3R5cGUiOiAibG9nb2ZmIiwKICAgICAgICAg',
    'ICAgICAgICAgICAgICAgInVzZXIiOiB1c2VybmFtZQogICAgICAgICAgICAgICAgICAgIH0pCiAgICAgICAgICAgICAgICAgICAgc2VuZF90b193ZWJob29rKHdlYmhvb2tfdXJsLCBiYXNlX3BheWxvYWQpCiAgICAgICAgICAgIAogICAgICAgICAgICAjIFByb2Nl',
    'c3MgQ3JlYXRlICg0Njg4KQogICAgICAgICAgICBlbGlmIGV2ZW50X2lkID09IEVWRU5UX1BST0NFU1NfQ1JFQVRFOgogICAgICAgICAgICAgICAgaWYgbW9uaXRvcl9wcm9jZXNzZXM6CiAgICAgICAgICAgICAgICAgICAgdXNlcm5hbWUgPSBldmVudC5nZXQoInN1',
    'YmplY3R1c2VybmFtZSIsICIiKQogICAgICAgICAgICAgICAgICAgIHByb2Nlc3NfbmFtZSA9IGV2ZW50LmdldCgicHJvY2Vzc25hbWUiLCAiIikKICAgICAgICAgICAgICAgICAgICBjb21tYW5kX2xpbmUgPSBldmVudC5nZXQoImNvbW1hbmRsaW5lIiwgIiIpCiAg',
    'ICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgIyBTYWRlY2Ugw7ZuZW1saSBwcm9jZXNzJ2xlcmkgYmlsZGlyIChvcHNpeW9uZWwgZmlsdHJlbGVtZSkKICAgICAgICAgICAgICAgICAgICBiYXNlX3BheWxvYWQudXBkYXRlKHsKICAgICAgICAg',
    'ICAgICAgICAgICAgICAgImV2ZW50X3R5cGUiOiAicHJvY2Vzc19jcmVhdGUiLAogICAgICAgICAgICAgICAgICAgICAgICAidXNlciI6IHVzZXJuYW1lLAogICAgICAgICAgICAgICAgICAgICAgICAicHJvY2Vzc19uYW1lIjogcHJvY2Vzc19uYW1lLAogICAgICAg',
    'ICAgICAgICAgICAgICAgICAiY29tbWFuZF9saW5lIjogY29tbWFuZF9saW5lCiAgICAgICAgICAgICAgICAgICAgfSkKICAgICAgICAgICAgICAgICAgICBzZW5kX3RvX3dlYmhvb2sod2ViaG9va191cmwsIGJhc2VfcGF5bG9hZCkKICAgICAgICAgICAgICAgICAg',
    'ICBsb2dnaW5nLmluZm8oZiJbUFJPQ0VTU10ge3VzZXJuYW1lfToge3Byb2Nlc3NfbmFtZX0iKQogICAgICAgICAgICAKICAgICAgICAgICAgIyBGaWxlIEFjY2VzcyAoNDY2MykKICAgICAgICAgICAgZWxpZiBldmVudF9pZCA9PSBFVkVOVF9GSUxFX0FDQ0VTUzoK',
    'ICAgICAgICAgICAgICAgIGlmIG1vbml0b3JfZmlsZV9hY2Nlc3M6CiAgICAgICAgICAgICAgICAgICAgdXNlcm5hbWUgPSBldmVudC5nZXQoInN1YmplY3R1c2VybmFtZSIsICIiKQogICAgICAgICAgICAgICAgICAgIG9iamVjdF9uYW1lID0gZXZlbnQuZ2V0KCJv',
    'YmplY3RuYW1lIiwgIiIpCiAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgYmFzZV9wYXlsb2FkLnVwZGF0ZSh7CiAgICAgICAgICAgICAgICAgICAgICAgICJldmVudF90eXBlIjogImZpbGVfYWNjZXNzIiwKICAgICAgICAgICAgICAgICAg',
    'ICAgICAgInVzZXIiOiB1c2VybmFtZSwKICAgICAgICAgICAgICAgICAgICAgICAgImZpbGVfcGF0aCI6IG9iamVjdF9uYW1lCiAgICAgICAgICAgICAgICAgICAgfSkKICAgICAgICAgICAgICAgICAgICBzZW5kX3RvX3dlYmhvb2sod2ViaG9va191cmwsIGJhc2Vf',
    'cGF5bG9hZCkKICAgICAgICAgICAgCiAgICAgICAgICAgICMgU1NIIEV2ZW50cyAoT3BlblNTSC9PcGVyYXRpb25hbCkKICAgICAgICAgICAgZWxpZiBldmVudC5nZXQoImxvZ19uYW1lIikgPT0gIk9wZW5TU0gvT3BlcmF0aW9uYWwiOgogICAgICAgICAgICAgICAg',
    'IyBTU0ggYmHFn2FyxLFzxLF6IGdpcmnFnwogICAgICAgICAgICAgICAgaWYgImZhaWxlZCIgaW4gbWVzc2FnZS5sb3dlcigpIG9yICJpbnZhbGlkIiBpbiBtZXNzYWdlLmxvd2VyKCk6CiAgICAgICAgICAgICAgICAgICAgaXBfbWF0Y2ggPSByZS5zZWFyY2gociIo',
    'XGQrXC5cZCtcLlxkK1wuXGQrKSIsIG1lc3NhZ2UpCiAgICAgICAgICAgICAgICAgICAgdXNlcl9tYXRjaCA9IHJlLnNlYXJjaChyInVzZXJbOlxzXSsoXFMrKSIsIG1lc3NhZ2UsIHJlLklHTk9SRUNBU0UpCiAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAg',
    'ICAgICAgICAgaWYgaXBfbWF0Y2ggYW5kIHVzZXJfbWF0Y2g6CiAgICAgICAgICAgICAgICAgICAgICAgIGlwID0gaXBfbWF0Y2guZ3JvdXAoMSkKICAgICAgICAgICAgICAgICAgICAgICAgdXNlciA9IHVzZXJfbWF0Y2guZ3JvdXAoMSkKICAgICAgICAgICAgICAg',
    'ICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIGlwIG5vdCBpbiB3aGl0ZWxpc3RfaXBzOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgZmFpbF9jb3VudCwgYmFuX3RyaWdnZXJlZCA9IHRyYWNrX2ZhaWxfYW5kX2NoZWNrX2JhbigKICAgICAg',
    'ICAgICAgICAgICAgICAgICAgICAgICAgICBpcCwgbm93X3RzLCB0aW1lX3dpbmRvd19zZWMsIG1heF9hdHRlbXB0cwogICAgICAgICAgICAgICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAg',
    'ICAgICBpZiBiYW5fdHJpZ2dlcmVkOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGJhbl9pcF93aW5kb3dzKGlwKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBiYXNlX3BheWxvYWQudXBkYXRl',
    'KHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiZXZlbnRfdHlwZSI6ICJzc2hfZmFpbGVkX2xvZ2luIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidXNlciI6IHVzZXIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImlw',
    'IjogaXAsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImZhaWxfY291bnRfd2luZG93IjogZmFpbF9jb3VudCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiYmFuX3RyaWdnZXJlZCI6IGJhbl90cmlnZ2VyZWQKICAgICAgICAgICAgICAg',
    'ICAgICAgICAgICAgIH0pCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBzZW5kX3RvX3dlYmhvb2sod2ViaG9va191cmwsIGJhc2VfcGF5bG9hZCkKICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgIyBTU0ggYmHFn2FyxLFsxLEgZ2lyacWfCiAgICAg',
    'ICAgICAgICAgICBlbGlmICJhY2NlcHRlZCIgaW4gbWVzc2FnZS5sb3dlcigpOgogICAgICAgICAgICAgICAgICAgIGlwX21hdGNoID0gcmUuc2VhcmNoKHIiKFxkK1wuXGQrXC5cZCtcLlxkKykiLCBtZXNzYWdlKQogICAgICAgICAgICAgICAgICAgIHVzZXJfbWF0',
    'Y2ggPSByZS5zZWFyY2gociJ1c2VyWzpcc10rKFxTKykiLCBtZXNzYWdlLCByZS5JR05PUkVDQVNFKQogICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgIGlmIGlwX21hdGNoIGFuZCB1c2VyX21hdGNoIGFuZCBhbGVydF9vbl9zdWNjZXNzOgog',
    'ICAgICAgICAgICAgICAgICAgICAgICBpcCA9IGlwX21hdGNoLmdyb3VwKDEpCiAgICAgICAgICAgICAgICAgICAgICAgIHVzZXIgPSB1c2VyX21hdGNoLmdyb3VwKDEpCiAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICBpZiBp',
    'cCBpbiBmYWlsX2V2ZW50czoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGZhaWxfZXZlbnRzW2lwXS5jbGVhcigpCiAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICBiYXNlX3BheWxvYWQudXBkYXRlKHsKICAgICAgICAg',
    'ICAgICAgICAgICAgICAgICAgICJldmVudF90eXBlIjogInNzaF9zdWNjZXNzX2xvZ2luIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ1c2VyIjogdXNlciwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJpcCI6IGlwCiAgICAgICAgICAgICAgICAg',
    'ICAgICAgIH0pCiAgICAgICAgICAgICAgICAgICAgICAgIHNlbmRfdG9fd2ViaG9vayh3ZWJob29rX3VybCwgYmFzZV9wYXlsb2FkKQogICAgCiAgICBleGNlcHQgS2V5Ym9hcmRJbnRlcnJ1cHQ6CiAgICAgICAgbG9nZ2luZy5pbmZvKCJbSU5GT10gS3VsbGFuxLFj',
    'xLEgdGFyYWbEsW5kYW4gZHVyZHVydWxkdS4iKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIGxvZ2dpbmcuZXJyb3IoZiJbRkFUQUxdIEJla2xlbm1leWVuIGhhdGE6IHtlfSIsIGV4Y19pbmZvPVRydWUpCgoKaWYgX19uYW1lX18gPT0gIl9fbWFp',
    'bl9fIjoKICAgIG1haW4oKQoK'
)
$pythonScriptBase64 = $base64Chunks -join ''

# Base64 string'i decode edip Python script'ini oluştur
# Newline karakterlerini kaldır (base64 satırlara bölünmüş olabilir)
$pythonScriptBase64 = $pythonScriptBase64 -replace '\s', ''
$pythonScript = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($pythonScriptBase64))

$pythonScript | Out-File -FilePath $ScriptPath -Encoding UTF8
Write-Host "       Script oluşturuldu: $ScriptPath" -ForegroundColor Green

Write-Host ""
Write-Host "[5/8] .env dosyası oluşturuluyor..." -ForegroundColor Yellow
if (-not (Test-Path $EnvPath)) {
    $envContent = @"
# Kullanıcı Aktivite İzleme Sistemi - Yapılandırma Dosyası (Windows)
# Değişiklik yaptıktan sonra: Restart-Service UserActivityMonitor

# ============================================
#  ZORUNLU AYARLAR
# ============================================

# n8n webhook URL (zorunlu) - BURAYI DÜZENLEYİN!
WEBHOOK_URL="https://n8vp.yeb.one/webhook/useractivity"

# ============================================
#  GÜVENLİK AYARLARI
# ============================================

# Kaç başarısız denemeden sonra IP banlansın?
MAX_ATTEMPTS=5

# Kaç saniyelik zaman penceresi içinde sayılacak? (örn: 120 = 2 dakika)
TIME_WINDOW_SEC=120

# Ban süresi (saniye) - şimdilik sadece bilgi amaçlı
BAN_DURATION=3600

# Banlanmayacak IP'ler (virgülle ayrılmış)
# Örnek: WHITELIST_IPS="1.2.3.4,5.6.7.8"
WHITELIST_IPS=""

# ============================================
#  SUNUCU BİLGİLERİ
# ============================================

# Sunucu adı (boş bırakırsan hostname kullanılır)
SERVER_NAME=""

# Sunucu IP (boş bırakırsan otomatik tespit edilir)
SERVER_IP=""

# Ortam bilgisi (Production, Staging, Development vb.)
SERVER_ENV="Production"

# ============================================
#  İZLEME AYARLARI
# ============================================

# Başarılı girişler için de bildirim gönderilsin mi? (1 = evet, 0 = hayır)
ALERT_ON_SUCCESS=1

# PowerShell komut geçmişini izle? (1 = evet, 0 = hayır)
MONITOR_COMMANDS=1

# Process oluşturma olaylarını izle? (1 = evet, 0 = hayır)
MONITOR_PROCESSES=1

# Login/logout olaylarını izle? (1 = evet, 0 = hayır)
MONITOR_LOGINS=1

# Dosya erişimlerini izle? (1 = evet, 0 = hayır) - File System Audit gerekir
MONITOR_FILE_ACCESS=0
"@
    $envContent | Out-File -FilePath $EnvPath -Encoding UTF8
    Write-Host "       .env dosyası oluşturuldu: $EnvPath" -ForegroundColor Green
    Write-Host ""
    Write-Host "       ⚠️  ÖNEMLİ: WEBHOOK_URL'i düzenlemeniz gerekiyor!" -ForegroundColor Yellow
    Write-Host "       Dosya: $EnvPath" -ForegroundColor Yellow
    Write-Host ""
} else {
    Write-Host "       .env dosyası zaten var, üzerine yazılmadı." -ForegroundColor Gray
}

Write-Host ""
Write-Host "[6/8] NSSM kontrol ediliyor..." -ForegroundColor Yellow
if (-not (Test-Path $NSSMPath)) {
    Write-Host "       NSSM bulunamadı." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "       NSSM'i otomatik indirmeyi deniyoruz..." -ForegroundColor Cyan
    
    # NSSM'i otomatik indirmeyi dene
    $nssmUrl = "https://nssm.cc/release/nssm-2.24.zip"
    $nssmZip = "$InstallDir\nssm.zip"
    $nssmExtract = "$InstallDir\nssm_extract"
    
    try {
        Write-Host "       NSSM indiriliyor..." -ForegroundColor Gray
        Invoke-WebRequest -Uri $nssmUrl -OutFile $nssmZip -UseBasicParsing -TimeoutSec 30
        Expand-Archive -Path $nssmZip -DestinationPath $nssmExtract -Force
        $nssmExe = Get-ChildItem -Path $nssmExtract -Recurse -Filter "nssm.exe" | Select-Object -First 1
        if ($nssmExe) {
            Copy-Item $nssmExe.FullName -Destination $NSSMPath -Force
            Remove-Item $nssmZip -Force -ErrorAction SilentlyContinue
            Remove-Item $nssmExtract -Recurse -Force -ErrorAction SilentlyContinue
            Write-Host "       ✓ NSSM otomatik indirildi ve kuruldu" -ForegroundColor Green
        } else {
            throw "nssm.exe bulunamadı"
        }
    } catch {
        Write-Host "       ⚠️  Otomatik indirme başarısız, manuel kurulum gerekli" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "       Manuel kurulum:" -ForegroundColor Cyan
        Write-Host "       1. https://nssm.cc/download adresinden indirin" -ForegroundColor White
        Write-Host "       2. nssm.exe dosyasını şuraya kopyalayın:" -ForegroundColor White
        Write-Host "          $NSSMPath" -ForegroundColor White
        Write-Host ""
        Write-Host "       Alternatif: Chocolatey ile kurulum:" -ForegroundColor Cyan
        Write-Host "       choco install nssm" -ForegroundColor White
        Write-Host ""
        
        $continue = Read-Host "       NSSM'i manuel olarak indirdiniz mi? (E/H)"
        if ($continue -ne "E" -and $continue -ne "e") {
            Write-Host "[HATA] NSSM gerekli, kurulum iptal edildi." -ForegroundColor Red
            exit 1
        }
        
        if (-not (Test-Path $NSSMPath)) {
            Write-Host "[HATA] NSSM hala bulunamadı: $NSSMPath" -ForegroundColor Red
            exit 1
        }
    }
} else {
    Write-Host "       ✓ NSSM bulundu" -ForegroundColor Green
}

Write-Host ""
Write-Host "[7/8] Windows Service kuruluyor..." -ForegroundColor Yellow

$existingService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existingService) {
    Write-Host "       Mevcut servis durduruluyor..." -ForegroundColor Gray
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
    Write-Host "       Mevcut servis kaldırılıyor..." -ForegroundColor Gray
    & $NSSMPath remove $ServiceName confirm
}

Write-Host "       Servis yükleniyor..." -ForegroundColor Gray
& $NSSMPath install $ServiceName $pythonPath $ScriptPath

if ($LASTEXITCODE -ne 0) {
    Write-Host "[HATA] Servis kurulumu başarısız!" -ForegroundColor Red
    exit 1
}

Write-Host "       Servis ayarları yapılandırılıyor..." -ForegroundColor Gray
& $NSSMPath set $ServiceName AppDirectory $InstallDir
& $NSSMPath set $ServiceName DisplayName "User Activity Monitor"
& $NSSMPath set $ServiceName Description "Comprehensive User Activity Monitor with n8n webhook and auto-ban for Windows"
& $NSSMPath set $ServiceName Start SERVICE_AUTO_START
& $NSSMPath set $ServiceName AppStdout "$LogDir\service_stdout.log"
& $NSSMPath set $ServiceName AppStderr "$LogDir\service_stderr.log"

Write-Host ""
Write-Host "[8/8] Servis başlatılıyor..." -ForegroundColor Yellow
Start-Service -Name $ServiceName

Start-Sleep -Seconds 2

$service = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($service -and $service.Status -eq "Running") {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "✓ Kurulum başarıyla tamamlandı!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Servis Bilgileri:" -ForegroundColor Cyan
    Write-Host "  Adı: $ServiceName" -ForegroundColor White
    Write-Host "  Durum: $($service.Status)" -ForegroundColor White
    Write-Host "  Script: $ScriptPath" -ForegroundColor White
    Write-Host "  Config: $EnvPath" -ForegroundColor White
    Write-Host "  Loglar: $LogDir" -ForegroundColor White
    Write-Host ""
    Write-Host "Yararlı Komutlar:" -ForegroundColor Cyan
    Write-Host "  Servis durumu:     Get-Service $ServiceName" -ForegroundColor White
    Write-Host "  Servis durdur:     Stop-Service $ServiceName" -ForegroundColor White
    Write-Host "  Servis başlat:     Start-Service $ServiceName" -ForegroundColor White
    Write-Host "  Servis yeniden:    Restart-Service $ServiceName" -ForegroundColor White
    Write-Host "  Logları görüntüle: Get-Content $LogDir\activity_monitor.log -Tail 50" -ForegroundColor White
    Write-Host ""
    Write-Host "⚠️  ÖNEMLİ: .env dosyasında WEBHOOK_URL'i düzenleyin!" -ForegroundColor Yellow
    Write-Host "   Dosya: $EnvPath" -ForegroundColor Yellow
    Write-Host "   Düzenleme sonrası: Restart-Service $ServiceName" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "📝 Örnek:" -ForegroundColor Cyan
    Write-Host "   notepad $EnvPath" -ForegroundColor White
    Write-Host "   # WEBHOOK_URL=`"https://your-n8n-url.com/webhook/...`" satırını düzenleyin" -ForegroundColor White
    Write-Host "   Restart-Service $ServiceName" -ForegroundColor White
    Write-Host ""
} else {
    Write-Host ""
    Write-Host "[UYARI] Servis kuruldu ancak başlatılamadı!" -ForegroundColor Yellow
    Write-Host "        Lütfen manuel olarak kontrol edin:" -ForegroundColor Yellow
    Write-Host "        Get-Service $ServiceName" -ForegroundColor White
    Write-Host "        Get-Content $LogDir\service_stderr.log" -ForegroundColor White
}

